### PR TITLE
merging 2.0 into 31162

### PR DESCRIPTION
**Pull request by gusreiber**

### CODE REVIEW

**Comment by gusreiber** [comment]
Looks huge. ...but maybe a lot has gone into 2.0?

**Comment by gusreiber** [comment]
...looks right as I am running it.

**Comment by recena** [comment]
@gusreiber My branch [JENKINS-31162] is updated from https://github.com/jenkinsci/jenkins/tree/2.0, Could you review the current conflicts? Please, don't hesitate to ping me for helping.

**Comment by gusreiber** [comment]
This branch was also attempting to fold in 2.0, but from Friday, so I am going to drop this PR and redo now that your branch is on 2.0

**Comment by recena** [comment]
@gusreiber I'm sorry, it was my mistake.

**Pull request closed without merging**
